### ISSUE TITLE
ajouter fleches survol slider

### ISSUE THREAD

**Issue by alesimancas** [WengerK/alejandra-chevey#24]
fleches pour le slider ci-joint

[arrows.zip](https://github.com/WengerK/alejandra-chevey/files/1761012/arrows.zip)

**Comment by WengerK** [comment]
![arrow-right-accessibility](https://user-images.githubusercontent.com/1841592/36805222-28d1ac54-1cbd-11e8-8a98-47d3d5ecd7d7.gif)

I can add 2 icons, So I added the `arrow-right`. It's pretty cool but the svg is invisible on a dark image ... :/ because no white border as a standard mouse cursor.

Do you want to fix it or not ?

**Comment by alesimancas** [comment]
leave it that way for the moment :)
